version: '3'
services:
  app : 
    container_name: docker-node-mongo
    restart: always
    build:
      context: ./dockerfiles
      dockerfile: app_node_mongo_Dockerfile
    ports:
      - '${APACHE_PORT}:3000'
    environment: 
      - 'APACHE_HOST=${APACHE_HOST}'
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'